### ISSUE TITLE
运行报错：cookie值 not a legal HTTP header value

### ISSUE THREAD

**Issue by QCHighing** [chenchenwuai/tieba-delete#1]
> tieba-delete@1.0.0 start
> node index

/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:684
		throw new TypeError(`${value} is not a legal HTTP header value`);
		      ^

TypeError: BAIDUID=F65849F783730.............................50b757c3
 is not a legal HTTP header value
    at validateValue (/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:684:9)
    at Headers.append (/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:836:3)
    at new Headers (/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:761:11)
    at new Request (/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:1231:19)
    at /home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:1439:19
    at new Promise (<anonymous>)
    at fetch (/home/dev/repos/tieba-delete/node_modules/node-fetch/lib/index.js:1437:9)
    at request (/home/dev/repos/tieba-delete/src/request.js:7:16)
    at getTBS (/home/dev/repos/tieba-delete/src/utils.js:5:26)
    at /home/dev/repos/tieba-delete/index.js:21:21

**Comment by chenchenwuai** [comment]
https://github.com/node-fetch/node-fetch/issues/401
在请求库里面找到了这个问题，是不是因为cookie里面有换行符或者其他特殊字符？例如`\n`

**Comment by chenchenwuai** [comment]
已修复这个问题
